baseURL = 'https://rwgb.github.io/'
languageCode = 'en-us'
title = 'Ralph Brynard | Developer & Creator'
theme = 'congo'

enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[params]
  colorScheme = "ocean"
  defaultAppearance = "dark"
  autoSwitchAppearance = true
  
  enableEmoji = true

[params.homepage]
  layout = "profile"
  homepageImage = "img/profile.jpg"
  showRecent = true
  showRecentItems = 6
  cardView = true
  cardViewScreenWidth = false

[params.article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showComments = false
  sharingLinks = ["twitter", "reddit", "linkedin", "email"]

[params.list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true

[params.footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Ralph Brynard | Developer & Creator"
    
    [languages.en.params]
      displayName = "EN"
      description = "Developer, creator, and technology enthusiast sharing projects and insights"
      
    [[languages.en.menu.main]]
      name = "Blog"
      pageRef = "posts"
      weight = 10
    [[languages.en.menu.main]]
      name = "Projects"
      pageRef = "projects"
      weight = 20
    [[languages.en.menu.main]]
      name = "About"
      pageRef = "about"
      weight = 30
    [[languages.en.menu.main]]
      name = "Contact"
      pageRef = "contact"
      weight = 40

    [languages.en.params.author]
      name = "Ralph Brynard"
      image = "img/profile.jpg"
      headline = "Developer & Content Creator"
      bio = "Building innovative projects and sharing knowledge through code, writing, and video. Passionate about open source and helping others learn."
      links = [
        { github = "https://github.com/rwgb" },
        { linkedin = "https://linkedin.com/in/ralphbrynard" },
        { youtube = "https://youtube.com/yourchannel" },
        { email = "mailto:ralph.brynard@gmail.com" }
      ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
