baseURL = 'https://rwgb.github.io/'
languageCode = 'en-us'
title = 'Ralph Brynard'
theme = 'congo'

[params]
  description = "Personal blog and projects"
  author = "Ralph Brynard"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/rwgb"
[[params.socialIcons]]
  name = "youtube"
  url = "https://youtube.com/yourchannel"
[[params.socialIcons]]
  name = "buymeacoffee"
  url = "https://buymeacoffee.com/rwgb"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3